### ISSUE TITLE
UHC無法正常開啟，錯誤：「網站資訊錯誤」

### ISSUE THREAD

**Issue by Hong4507** [lulu2002/DatouUHC-Issues#10]
**請問您的遊戲版本為？**
Paper 1.8.8

**請問您的 Java 版本為？ ([查看方式](https://pclevinblog.pixnet.net/blog/post/314562265-%5Bjava%5Djava%E5%A6%82%E4%BD%95%E6%9F%A5%E7%9C%8B%E7%89%88%E6%9C%AC%E4%BD%8D%E5%85%83))**
Java 8

**請問 Bug 的內容是？**
UHC插件無法正常啟動，錯誤訊息顯示「網站資訊錯誤」

**請問是怎麼觸發這個 Bug 的呢？**
單純開啟伺服器，沒有多餘的動作

**媒體提供**
![7DABC84F-D42E-4F02-A01D-061B5ECDEA3B](https://user-images.githubusercontent.com/62610544/154832610-204ca3c4-8e59-4c5e-b980-d946857f7fba.png)

`DaTouUHC 3.1.0 encountered an aA
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_321
Plugins: WorldBorder v1.8.7, DiscordSRV v1.19.1, custom-ore-generator v2020.07.12, Datoucmd v1.0-SNAPSHOT, PacketListenerApi v3.7.6-SNAPSHOT, DaTouUHC v3.1.0
----------------------------------------------------------------------------------------------
More Information: 
網站資訊錯誤。 請將此問題回報至 &bhttps://discord.gg/FgjWsp7&c.
aA Report: 網站資訊錯誤。 請將此問題回報至 &bhttps://discord.gg/FgjWsp7&c.
     at me.lulu.datouuhc.goto. .H.do(SourceFile:81)
     at me.lulu.datouuhc.goto. .dZ.for(SourceFile:79)
     at me.lulu.datouuhc.goto. .dZ.if(SourceFile:75)
     at me.lulu.datouuhc.goto. .dZ.if(SourceFile:57)
     at me.lulu.datouuhc.goto. .dZ.do(SourceFile:32)
     at me.lulu.datouuhc.UHCPlugin.if(SourceFile:91)
     at me.lulu.datouuhc.goto. .bH.onEnable(SourceFile:310)
     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
----------------------------------------------------------------------------------------------`

**Comment by lulu2002** [comment]
感謝回報，目前正在加緊修復當中！

**Comment by lulu2002** [comment]
已修正！
